name: elk-stack

networks:
  elk-net:
    name: elk-net
    driver: bridge

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es01
    restart: unless-stopped
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
      # Security an, TLS aktiviert
      - xpack.security.enabled=true
      # Logs in Datei (wird gemountet)
      - path.logs=/usr/share/elasticsearch/logs
      # Benutzerpasswort (Superuser)
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /mnt/elastic_logs/elasticsearch/data:/usr/share/elasticsearch/data
      - /mnt/elastic_logs/elasticsearch/logs:/usr/share/elasticsearch/logs
      - ./configs/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./certs:/usr/share/elasticsearch/config/certs:ro
    networks:
      - elk-net

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    restart: unless-stopped
    depends_on:
      - es01
    environment:
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=${KIBANA_SERVICE_TOKEN}
      # Optional: öffentlich erreichbare Basis-URL (für Links)
      - SERVER_PUBLICBASEURL=${KIBANA_PUBLIC_URL:-https://kibana.local}
    volumes:
      - ./configs/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - /mnt/elastic_logs/kibana/logs:/usr/share/kibana/logs
      - ./certs:/usr/share/kibana/config/certs:ro
    networks:
      - elk-net

  fleet-server:
    image: docker.elastic.co/beats/elastic-agent:${STACK_VERSION}
    container_name: fleet-server
    restart: unless-stopped
    depends_on:
      - es01
      - kibana
    environment:
      # Fleet Server mit TLS an ES/Kibana koppeln
      - FLEET_SERVER_ENABLE=1
      - FLEET_SERVER_ELASTICSEARCH_HOST=https://es01:9200
      - FLEET_SERVER_ELASTICSEARCH_CA=/usr/share/elastic-agent/certs/ca.crt
      - FLEET_SERVER_CERT=/usr/share/elastic-agent/certs/fleet-server.crt
      - FLEET_SERVER_CERT_KEY=/usr/share/elastic-agent/certs/fleet-server.key
      - KIBANA_HOST=https://kibana:5601
      - KIBANA_CA=/usr/share/elastic-agent/certs/ca.crt
      - KIBANA_USERNAME=elastic
      - KIBANA_PASSWORD=${ELASTIC_PASSWORD}
      # Gemeinsame ES-Creds (werden auch vom Agent genutzt)
      - ELASTICSEARCH_HOST=https://es01:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_CA=/usr/share/elastic-agent/certs/ca.crt
      - LOG_LEVEL=info
    volumes:
      # Persistente Agent-/Fleet-Server-Daten & -Logs
      # Wichtig: Nur das Datenverzeichnis mounten – ein Bind auf /usr/share/elastic-agent
      # würde das Agent-Binary überschreiben und der Container könnte nicht starten.
      - /mnt/elastic_logs/fleet-server/agent:/usr/share/elastic-agent/data
      - /mnt/elastic_logs/fleet-server/logs:/var/log/elastic-agent
      - ./certs:/usr/share/elastic-agent/certs:ro
    networks:
      - elk-net

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    depends_on:
      - es01
      - kibana
      - fleet-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/etc/caddy/certs:ro
    networks:
      - elk-net
