server.host: 0.0.0.0
server.publicBaseUrl: ${SERVER_PUBLICBASEURL:https://kibana.local}
server.ssl.enabled: true
server.ssl.certificate: /usr/share/kibana/config/certs/kibana.crt
server.ssl.key: /usr/share/kibana/config/certs/kibana.key

# Verbindung zu ES über Service-Account-Token
elasticsearch.hosts: ["https://es01:9200"]
elasticsearch.serviceAccountToken: ${ELASTICSEARCH_SERVICEACCOUNTTOKEN}
elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/certs/ca.crt"]
elasticsearch.ssl.verificationMode: certificate

# File-Logging aktivieren (statt nur stdout)
logging:
  appenders:
    file:
      type: file
      fileName: /usr/share/kibana/logs/kibana.log
      layout:
        type: json
  root:
    level: info
    appenders: [file]
