server.host: 0.0.0.0
server.publicBaseUrl: ${SERVER_PUBLICBASEURL:http://localhost:5601}

# Verbindung zu ES über Service-Account-Token
elasticsearch.hosts: ["http://es01:9200"]
elasticsearch.serviceAccountToken: ${ELASTICSEARCH_SERVICEACCOUNTTOKEN}

# File-Logging aktivieren (statt nur stdout)
logging:
  appenders:
    file:
      type: file
      fileName: /usr/share/kibana/logs/kibana.log
      layout:
        type: json
  root:
    level: info
    appenders: [file]
