server.host: 0.0.0.0
server.publicBaseUrl: ${SERVER_PUBLICBASEURL:http://localhost:5601}

# Verbindung zu ES (hier via Superuser – für Produktion separat absichern!)
elasticsearch.hosts: ["http://es01:9200"]
elasticsearch.username: ${ELASTICSEARCH_USERNAME:elastic}
elasticsearch.password: ${ELASTIC_PASSWORD}

# File-Logging aktivieren (statt nur stdout)
logging:
  appenders:
    file:
      type: file
      fileName: /usr/share/kibana/logs/kibana.log
      layout:
        type: json
  root:
    level: info
    appenders: [file]

xpack.security.enabled: true
