cluster.name: docker-cluster
node.name: es01
discovery.type: single-node

# Logging-Tuning (optional)
logger.level: info

# Sicherheit aktivieren und TLS für HTTP/Transport einschalten
xpack.security.enabled: true
xpack.security.http.ssl:
  enabled: true
  certificate: /usr/share/elasticsearch/config/certs/es01.crt
  key: /usr/share/elasticsearch/config/certs/es01.key
  certificate_authorities: ["/usr/share/elasticsearch/config/certs/ca.crt"]
xpack.security.transport.ssl:
  enabled: true
  verification_mode: certificate
  certificate: /usr/share/elasticsearch/config/certs/es01.crt
  key: /usr/share/elasticsearch/config/certs/es01.key
  certificate_authorities: ["/usr/share/elasticsearch/config/certs/ca.crt"]

path:
  data: /usr/share/elasticsearch/data
  logs: /usr/share/elasticsearch/logs

# Für Docker-Umgebungen üblich:
network.host: 0.0.0.0
